# Generated by Django 5.0 on 2023-12-29 18:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('AUD', 'AUD'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('NOK', 'NOK'), ('SEK', 'SEK'), ('USD', 'USD')], max_length=5)),
                ('nome', models.CharField(choices=[('Dólar australiano', 'Dólar australiano'), ('Dólar canadense', 'Dólar canadense'), ('Franco suíço', 'Franco suíço'), ('Coroa dinamarquesa', 'Coroa dinamarquesa'), ('Euro', 'Euro'), ('Libra Esterlina', 'Libra Esterlina'), ('Iene', 'Iene'), ('Coroa norueguesa', 'Coroa norueguesa'), ('Coroa sueca', 'Coroa sueca'), ('Dólar dos Estados Unidos', 'Dólar dos Estados Unidos')], max_length=50)),
                ('valor', models.FloatField(default=0)),
                ('dataCotacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('AUD', 'AUD'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('NOK', 'NOK'), ('SEK', 'SEK'), ('USD', 'USD')], max_length=5)),
                ('nome', models.CharField(choices=[('Dólar australiano', 'Dólar australiano'), ('Dólar canadense', 'Dólar canadense'), ('Franco suíço', 'Franco suíço'), ('Coroa dinamarquesa', 'Coroa dinamarquesa'), ('Euro', 'Euro'), ('Libra Esterlina', 'Libra Esterlina'), ('Iene', 'Iene'), ('Coroa norueguesa', 'Coroa norueguesa'), ('Coroa sueca', 'Coroa sueca'), ('Dólar dos Estados Unidos', 'Dólar dos Estados Unidos')], max_length=50)),
            ],
        ),
    ]
